lexik_paybox_sample_call:
    pattern:  /
    defaults: { _controller: LexikPayboxBundle:Sample:index }

lexik_paybox_sample_return:
    pattern:  /payment/return/{status}
    defaults: { _controller: LexikPayboxBundle:Sample:return, status: error }
    requirements:
        status: success|canceled|denied
