parameters:
   lexik_paybox.request_handler.class: Lexik\Bundle\PayboxBundle\Service\PayboxRequest

services:
   lexik_paybox.request_handler:
       class:     %lexik_paybox.request_handler.class%
       arguments: [%lexik_paybox.parameters%, %lexik_paybox.servers%, @form.factory]
