language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION=2.7.*
  
matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer require symfony/form:${SYMFONY_VERSION} --no-update
  - composer require symfony/options-resolver:${SYMFONY_VERSION} --no-update
  - composer update --dev

script: phpunit
